<?xml version="1.0" encoding="utf-8"?><Database Name="ESSInternet" Class="CitizenDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ALICO-PC;Initial Catalog=ESSInternet;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ESSInternetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Citizens" Member="Citizens">
    <Type Name="Citizen">
      <Column Name="IdentityNo" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BirthPlace" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MotherName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FatherName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Voters" Member="Voters">
    <Type Name="Voter">
      <Column Name="IdentityNo" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BirthPlace" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MotherName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FatherName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="RegionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedFrom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VoterStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BiometricPath" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Handicapped" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
    </Type>
  </Table>
</Database>